[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

fuzz = { runs = 1000, max_test_rejects = 65536 }

[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
